name: build-deploy

on:
  workflow_dispatch:

jobs:
  build:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'

      - uses: actions/download-artifact@v3
        with:
          name: toernooinl2googlecalendar-1.0-full.jar

      - name: Run
        run: java -jar toernooinl2googlecalendar-1.0-full.jar

