name: Run For PBO

on:
  workflow_dispatch:
  schedule:
    # 0 5 * * 1,3,5:  Every monday, wednesday, friday at 5AM"
    - cron: "0 5 * * *"
jobs:
  build:
    name: Run
    runs-on: ubuntu-latest
    environment: PBO_PROD
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: "tags/1.0"
          file: toernooinl2googlecalendar-1.0-full.jar

      - name: Configure secrets in config
        env:
          CLIENT_ID: ${{secrets.CLIENT_ID}}
          CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
          REFRESH_TOKEN: ${{secrets.REFRESH_TOKEN}}
        run: |-
          sed -i "s|CLIENT_ID|$CLIENT_ID|g" "config/client_secret_template.json"
          sed -i "s|CLIENT_SECRET|$CLIENT_SECRET|g" "config/client_secret_template.json"
          sed -i "s|ACCESS_TOKEN|$ACCESS_TOKEN|g" "config/calendar_secret_template.json"
          sed -i "s|REFRESH_TOKEN|$REFRESH_TOKEN|g" "config/calendar_secret_template.json"

          cat config/client_secret_template.json
          cat config/calendar_secret_template.json
        shell: bash

      # Create dummy commit when needed to keep repo alive (workaround)
      # https://github.com/gautamkrishnar/keepalive-workflow
      - uses: gautamkrishnar/keepalive-workflow@v1

      - name: Run
        run: java -Dconfig=config/config-template.xml -jar toernooinl2googlecalendar-1.0-full.jar

