name: Run For PBO

on:
  workflow_dispatch:

jobs:
  build:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: "tags/1.0"
          file: toernooinl2googlecalendar-1.0-full.jar

      - name: Run
        run: java -jar toernooinl2googlecalendar-1.0-full.jar

